DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS user;

CREATE TABLE film (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT UNIQUE NOT NULL,
  regista TEXT NOT NULL,
  visto BOOLEAN NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);
